#
# Docker Compose
#

version: '3.7'

services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "4000:80"
        networks:
            - netapp
        depends_on:
            - backend
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        networks:
            - netapp
networks:
    netapp:
