INSERT INTO servidor (nome, cpf, matricula, orgao) VALUES ('José da Siva', '92792208023', 'CB10102', 'SEPLAG');
INSERT INTO servidor (nome, cpf, matricula, orgao) VALUES ('Marcos Pinheiro', '71132403057', 'CB10103', 'SEPLAG');
INSERT INTO servidor (nome, cpf, matricula, orgao) VALUES ('Marta Soares', '50995969086', 'CB10107', 'SEFIN');
INSERT INTO servidor (nome, cpf, matricula, orgao) VALUES ('Jennifen Gomes', '84785399058', 'CB10199', 'SEFIN');
INSERT INTO beneficio (tipo_beneficio, servidor_id) VALUES ('APOSENTADORIA', 1);
INSERT INTO beneficio (tipo_beneficio, servidor_id) VALUES ('APOSENTADORIA', 2);
INSERT INTO beneficio (tipo_beneficio, servidor_id) VALUES ('APOSENTADORIA', 3);
INSERT INTO beneficio (tipo_beneficio, servidor_id) VALUES ('APOSENTADORIA', 4);
INSERT INTO tramitacao_movimento (beneficio_id, setor_origem, setor_destino, data_movimentacao) VALUES (1, 'SECRETARIA', 'ANALISE', TIMESTAMP WITH TIME ZONE '2005-12-31 07:30:02Z');
INSERT INTO tramitacao_movimento (beneficio_id, setor_origem, setor_destino, data_movimentacao) VALUES (1, 'ANALISE', 'COMITE_GESTOR', TIMESTAMP WITH TIME ZONE '2006-01-31 10:59:10Z');