export enum TipoDocumentoBeneficio {
    IDENTIFICACAO = 'IDENTIFICACAO',
    VIDA_FUNCIONAL = 'VIDA_FUNCIONAL',
    CONTAGEM_TEMPO = 'CONTAGEM_TEMPO',
    REMUNERACAO_PROVENTOS = 'REMUNERACAO_PROVENTOS'
}
